CREATE TABLE CUSTOMERS
(
    ID           SERIAL PRIMARY KEY,
    NAME         VARCHAR(250),
    SURNAME      VARCHAR(250),
    AGE          INT,
    PHONE_NUMBER INT
);

CREATE TABLE ORDERS
(
    ID           SERIAL PRIMARY KEY,
    DATE         DATE DEFAULT CURRENT_DATE,
    CUSTOMER_ID  INT,
    PRODUCT_NAME VARCHAR(250),
    AMOUNT       INT,
    CONSTRAINT FK_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
            REFERENCES CUSTOMERS (ID)
);

INSERT INTO CUSTOMERS (NAME, SURNAME, AGE)
VALUES ('ALEXEY', 'PETROV', 22);

INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, AMOUNT)
VALUES (1, 'KOTYA SHAPKA', 50);